#!/usr/bin/python3
#coding:utf-8
from selenium import  webdriver
from selenium.webdriver.common.by import By
import time

browser = webdriver.Chrome()
url = "http://mail.sunyard.com/"
#最大化浏览器
# browser.maximize_window()
# 最小化
# browser.minimize_window()
#全屏
# browser.fullscreen_window()
#设置大小
# browser.set_window_size(400,800)
browser.get(url)
#HTML中id 是唯一标识
# browser.find_element_by_id("qquin").clear()
#键入信息
# browser.find_element_by_id("qquin").send_keys("aaa")
# time.sleep(1)
# browser.find_element_by_id("qquin").clear()
#
# #HTML中name来指定元素名称,不唯一
# browser.find_element_by_name("qquin").send_keys("bbb")
# time.sleep(1)
# browser.find_element_by_id("qquin").clear()
#
# #HTML中class 类名称,通过属性查找,
# browser.find_element_by_class_name("self_input").send_keys("ccc")
# time.sleep(1)
# browser.find_element_by_class_name("self_input").clear()

#tag定位
# browser.find_element_by_tag_name()

#link定位
# browser.find_element_by_link_text("管理员登陆")
#link的补充,部分文本定位
# time.sleep(1)
# 获得文本
# print(browser.find_element_by_partial_link_text("管理员").text)
#获得大小
# print(browser.find_element_by_partial_link_text("管理员").size)
#获得属性
print(browser.find_element_by_partial_link_text("管理员").get_attribute('href'))
print(browser.find_element_by_partial_link_text("管理员").get_property('class'))
# print(browser.find_element_by_partial_link_text("管理员").location)
# #点击
# browser.find_element_by_partial_link_text("管理员").click()

#XPath 定位
#绝对路径定位
#利用元素定位 //* 任意路径下 属性 id  等于 qquin
# browser.find_element_by_xpath('//*[@id="qquin"]').send_keys("dd")
# time.sleep(1)
# browser.find_element_by_xpath('//input[@id="qquin"]').send_keys("ee")
# time.sleep(1)
# browser.find_element_by_xpath('//input[@name="qquin"]').send_keys("ff")
# #通过父级查询
# time.sleep(1)
# #通过逻辑运算符
# browser.find_element_by_xpath('//input[@id="qquin" and @name="qquin"]').send_keys("gg")
# time.sleep(2)
# browser.find_element_by_class_name("self_input").clear()
#
# #css选择器
# #. 表示class 的名字
# browser.find_element_by_css_selector(".self_input").send_keys("hh")
# time.sleep(1)
# ##表示通过id定位
# browser.find_element_by_css_selector("#qquin").send_keys("II")
# time.sleep(1)
#直接使用标签定位
# browser.find_element_by_css_selector("input").send_keys("JJ")
# time.sleep(1)
#父子关系定位,属性定位,组合定位
# browser.find_element_by_css_selector("div>div>span>input[id='qquin']").send_keys("KK")

#定位方式                           Xpath                              CSS
#标签                             //div                                div
#By id                            //div[@id='eleid']                   div#eleid
#By class                         //div[@class='eleclass']             div.eleclass
#By 属性                          //div[title='Move mouse here']       div[title=Move mouse here]
#                                                                      div[title^=Move]
#                                                                      div[title$=here]
#                                                                      div[title*=mouse]
#定位子元素                       //div[@id=''eleid]/*                 div#eleid>*
#                                 //div/h1                             div>h1

#统一方法
# browser.find_element(By.NAME,'qquin').send_keys('MM')
# browser.find_element(By.ID,'qquin').send_keys('nn')
# browser.find_element(By.CLASS_NAME,'self_input').send_keys('nn')
# browser.find_element(By.XPATH,'//input[@name="qquin"]').send_keys("oo")
# browser.find_element(By.CSS_SELECTOR,'#qquin').send_keys("PP")

#前进后退
#点击连接
time.sleep(1)
browser.find_element_by_partial_link_text("管理员").click()
time.sleep(2)
#后退
browser.back()
time.sleep(2)
#前进
browser.forward()
#shuaxin
browser.refresh()
